// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Certificate struct {
	Certificate string `json:"certificate"`
	Key         string `json:"key"`
	Expiry      string `json:"expiry"`
}

type NewCertificate struct {
	CommonName         string  `json:"commonName"`
	Organization       *string `json:"organization"`
	OrganizationalUnit *string `json:"organizationalUnit"`
	Locality           *string `json:"locality"`
	Province           *string `json:"province"`
	Country            *string `json:"country"`
}
